%%{init: {
  "themeCSS": ".classGroup rect{fill:#EEF5FF!important;stroke:#2A5DB0!important;stroke-width:1.4px!important;} .classTitle{font-weight:700!important;} .relation{stroke:#2A5DB0!important;}"
}}%%
