%%{init: {
  "themeCSS": ".er.entityBox{fill:#EEF5FF!important;stroke:#2A5DB0!important;} .er.attributeBoxOdd{fill:#FFFFFF!important;} .er.attributeBoxEven{fill:#F2F7FD!important;} .er.relationshipLabelBox{fill:#F6FAFF!important;}"
}}%%
