%%{init: {
  "gitGraph": { "mainBranchName": "main", "showBranches": true, "showCommitLabel": true },
  "themeCSS": ".arrow{stroke-width:3px!important;} .branch{stroke-width:1.6px!important;stroke-dasharray:0!important;} .commit-label{font-size:9px!important;} .commit-label-bkg{opacity:0.78!important;}"
}}%%
