%%{init: {
  "pie": { "textPosition": 0.62 },
  "themeCSS": ".pieTitleText{font-weight:700!important;fill:#0F223A!important;} .slice{stroke:#FFFFFF!important;stroke-width:2px!important;} .legend text{fill:#0F223A!important;}"
}}%%
