%%{init: {
  "themeCSS": ".node rect{stroke:#2A5DB0!important;stroke-width:1.2px!important;} .node text{fill:#0F223A!important;font-weight:600!important;} .link{fill:none!important;stroke-opacity:0.32!important;}"
}}%%
