%%{init: {
  "sequence": { "mirrorActors": false, "showSequenceNumbers": true, "messageAlign": "center", "actorMargin": 70, "boxMargin": 10 },
  "themeCSS": ".actor{stroke:#2A5DB0!important;fill:#ECF4FF!important;} .messageText,.loopText,.labelText{fill:#0F223A!important;} .sequenceNumber{fill:#2A5DB0!important;} .note{fill:#F6FAFF!important;stroke:#6F9DCE!important;}"
}}%%
