%%{init: {
  "themeCSS": ".stateGroup rect,.stateGroup polygon{fill:#ECF4FF!important;stroke:#2A5DB0!important;stroke-width:1.4px!important;} .transition{stroke:#2A5DB0!important;} .state-title{fill:#0F223A!important;font-weight:700!important;}"
}}%%
