%%{init: {
  "themeCSS": ".timeline-node text,.timeline-node tspan{fill:#0F223A!important;} .timeline-node .node-bkg{stroke-width:1.4px!important;} .eventWrapper{filter:none!important;} .lineWrapper line{stroke:#2A5DB0!important;stroke-width:2px!important;}"
}}%%
