kanban
  {{backlog}}
    docs[Document contract]@{ assigned: "BZ", ticket: "DIA-101", priority: "High" }
    web[Wire web consumer]@{ assigned: "BZ", ticket: "DIA-102", priority: "Medium" }
  {{doing}}
    style[Benizar style]@{ assigned: "BZ", ticket: "DIA-121", priority: "Very High" }
  {{done}}
    slides[Extract from slides]@{ assigned: "BZ", ticket: "DIA-081", priority: "Low" }
